w4d5/music/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :bands
end

w4d5/music/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

w4d5/music/app/models/band.rb
class Band < ApplicationRecord

  validates :name, presence: true

  def method_name

  end
end

w4d5/music/app/models/user.rb
class User < ApplicationRecord

  validates :email, :password_digest, :session_token, presence: true
  validates :email, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true }

  before_validation :ensure_session_token

  attr_reader :password

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    if user && user.is_password?(password)
      user
    else
      nil
    end
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest) == password
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= self.reset_session_token!
  end

end

w4d5/music/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def login(user)
    session[:session_token] = user.reset_session_token!
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def require_login
    # redirect_to musics_url unless logged_in?
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

end

w4d5/music/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if @user
      login!(@user)
      redirect_to user_url(@user)
    else
      @user = User.new
      flash.now[:errors] = 'WRONG'
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

w4d5/music/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def destroy

  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

w4d5/music/app/helpers/application_helper.rb
module ApplicationHelper
end

w4d5/music/app/helpers/users_helper.rb
module UsersHelper
end

w4d5/music/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <% if logged_in? %>
      Hello <%= @user.email %> !
      <form  action="<%= session_url %>" method="post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="delete">
        <input type="submit" value="Log Out Bruh">
      </form>

    <% else %>
      <a href="<%= new_user_url %>">Sign up!</a>
      <a href="<%= new_session_url %>">Log In!</a>
      
    <% end %>
  </header>
  <h1> THE WORST MUSIC APP EVER THERE AINT EVEN MUSIC </h1>

    <%= flash.now[:errors] %>
    <%= yield %>
  </body>
</html>

w4d5/music/app/views/users/new.html.erb
<form action="<%= users_url %>" method="post">

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label> Email
    <input type="text" name="user[email]" value="<%= @user.email %> ">
  </label>

  <label> Password
    <input type="password" name="user[password]" value="<%= @user.password %>">
  </label>

  <input type="submit" value="Sign Up!">

</form>

w4d5/music/app/views/users/show.html.erb
<h1> Hello! </h1>